<?php

$manifest = array(
	'acceptagle_sugar_flavors' => array(
		'PRO', 'ENT'
	),
	'acceptable_sugar_versions' => array(),
	'readme' => '',
	'key' => 'lg',
	'author' => 'Lampada Global',
	'description' => 'Lampada Portal for SugarCRM',
	'icon' => '',
	'is_uninstallable' => true,
	'name' => 'LampadaPortal',
	'published_date' => '2010-12-21	12:00:00',
	'type' => 'module',
	'version' => '2.0',
	'remove_tables' => 'prompt',
);
$installdefs = array(
	'id' => 'lg',
	'image_dir' => '<basepath>/icons',
	'beans' =>
	array(
		array(
			'module' => 'lg_PortalUser',
			'class' => 'lg_PortalUser',
			'path' => 'modules/lg_PortalUser/lg_PortalUser.php',
			'tab' => true,
		),
	),
	'layoutdefs' => array(),
	'relationships' => array(
       array(
         'module'          => 'lg_PortalUser',
         'meta_data'       => '<basepath>/SugarModules/relationships/contacts_lg_portaluserMetaData.php',
        ),
    ),
	'copy' =>
	array(
		array(
			'from' => '<basepath>/iportal',
			'to' => 'iportal',
		),
		array(
			'from' => '<basepath>/install_files/iportal.php',
			'to' => 'iportal.php',
		),
		array(
			'from' => '<basepath>/install_files/iportal_config.php',
			'to' => 'iportal_config.php',
		),
		array(
			'from' => '<basepath>/install_files/iportal_download.php',
			'to' => 'iportal_download.php',
		),
		array(
			'from' => '<basepath>/install_files/iportalTreeData.php',
			'to' => 'iportalTreeData.php',
		),
		array(
			'from' => '<basepath>/install_files/scripts/sugarportal.js',
			'to' => 'sugarportal.js',
		),
		array(
			'from' => '<basepath>/install_files/include/iportalEntryPoint.php',
			'to' => 'include/iportalEntryPoint.php',
		),
//Custom modules
		array(
			'from' => '<basepath>/SugarModules/modules/lg_PortalUser',
			'to' => 'modules/lg_PortalUser',
		),
//Authentication
		array(
			'from' => '<basepath>/SugarModules/modules/Users/authentication/IportalAuthenticate',
			'to' => 'modules/Users/authentication/IportalAuthenticate',
		),
//Smarty Plugins
		array(
			'from' => '<basepath>/install_files/include/Smarty/plugins/function.iportal_link.php',
			'to' => 'include/Smarty/plugins/function.iportal_link.php',
		),
		array(
			'from' => '<basepath>/install_files/include/Smarty/plugins/function.iportal_button.php',
			'to' => 'include/Smarty/plugins/function.iportal_button.php',
		),
//Sugar Fields
		array(
			'from' => '<basepath>/SugarModules/custom/include/SugarFields/Fields/IRelate',
			'to' => 'custom/include/SugarFields/Fields/IRelate',
		),
		array(
			'from' => '<basepath>/SugarModules/custom/modules/Cases/Caseslogic_hooks.php',
			'to' => 'custom/modules/Cases/Caseslogic_hooks.php',
		),
// copy all custom modules
		array(
			'from' => '<basepath>/SugarModules/custom/modules/Accounts',
			'to' => 'custom/modules/Accounts',
		),
		array(
			'from' => '<basepath>/SugarModules/custom/modules/Bugs',
			'to' => 'custom/modules/Bugs',
		),
		array(
			'from' => '<basepath>/SugarModules/custom/modules/Cases',
			'to' => 'custom/modules/Cases',
		),
		array(
			'from' => '<basepath>/SugarModules/custom/modules/Contacts',
			'to' => 'custom/modules/Contacts',
		),
		array(
			'from' => '<basepath>/SugarModules/custom/modules/KBDocuments',
			'to' => 'custom/modules/KBDocuments',
		),
		array(
			'from' => '<basepath>/SugarModules/custom/modules/Notes',
			'to' => 'custom/modules/Notes',
		),
	),
	'vardefs' =>
	array(
		array(
			'from' => '<basepath>/SugarModules/custom/Extension/modules/Bugs/Ext/Vardefs/sugarfield_show_in_portal_c.php',
			'to_module' => 'Bugs',
		),
		array(
			'from' => '<basepath>/SugarModules/custom/Extension/modules/Cases/Ext/Vardefs/sugarfield_contact_c.php',
			'to_module' => 'Cases',
		),
		array(
			'from' => '<basepath>/SugarModules/custom/Extension/modules/Cases/Ext/Vardefs/sugarfield_contact_id_c.php',
			'to_module' => 'Cases',
		),
		array(
			'from' => '<basepath>/SugarModules/custom/Extension/modules/Cases/Ext/Vardefs/sugarfield_show_in_portal_c.php',
			'to_module' => 'Cases',
		),
		array(
			'from' => '<basepath>/SugarModules/custom/Extension/modules/KBDocuments/Ext/Vardefs/sugarfield_show_in_portal_c.php',
			'to_module' => 'KBDocuments',
		),
		array(
			'from' => '<basepath>/SugarModules/custom/Extension/modules/Notes/Ext/Vardefs/sugarfield_show_in_portal_c.php',
			'to_module' => 'Notes',
		),

        array(
			'from' => '<basepath>/SugarModules/relationships/vardefs/contacts_lg_portaluser_Contacts.php',
			'to_module' => 'Contacts',
		),
        array(
			'from' => '<basepath>/SugarModules/relationships/vardefs/contacts_lg_portaluser_lg_PortalUser.php',
			'to_module' => 'lg_PortalUser',
		),
	),
	'language' =>
	array(
		array(
			'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
			'to_module' => 'application',
			'language' => 'en_us',
		),
		array(
			'from' => '<basepath>/SugarModules/language/application/pt_br.lang.php',
			'to_module' => 'application',
			'language' => 'pt_br',
		),
		array(
			'from' => '<basepath>/SugarModules/language/Contacts/en_us.lang.php',
			'to_module' => 'Contacts',
			'language' => 'en_us',
		),
		array(
			'from' => '<basepath>/SugarModules/language/Contacts/pt_br.lang.php',
			'to_module' => 'Contacts',
			'language' => 'pt_br',
		),
		array(
			'from' => '<basepath>/SugarModules/language/Cases/en_us.lang.php',
			'to_module' => 'Cases',
			'language' => 'en_us',
		),
		array(
			'from' => '<basepath>/SugarModules/language/Cases/pt_br.lang.php',
			'to_module' => 'Cases',
			'language' => 'pt_br',
		),
		array(
			'from' => '<basepath>/SugarModules/language/Accounts/en_us.lang.php',
			'to_module' => 'Accounts',
			'language' => 'en_us',
		),
		array(
			'from' => '<basepath>/SugarModules/language/Bugs/en_us.lang.php',
			'to_module' => 'Bugs',
			'language' => 'en_us',
		),
		array(
			'from' => '<basepath>/SugarModules/language/KBDocuments/en_us.lang.php',
			'to_module' => 'KBDocuments',
			'language' => 'en_us',
		),
		array(
			'from' => '<basepath>/SugarModules/language/Notes/en_us.lang.php',
			'to_module' => 'Notes',
			'language' => 'en_us',
		),
		array(
			'from' => '<basepath>/SugarModules/language/lg_PortalUser/en_us.lang.php',
			'to_module' => 'lg_PortalUser',
			'language' => 'en_us',
		),
	),
	'menu' =>
	array(
		array(
			'from' => '<basepath>/SugarModules/menus/Contacts.php',
			'to_module' => 'Contacts',
		),
	),
	'custom_fields' =>
	array(
      array (
        'name' => 'contact_c',
        'label' => 'LBL_CONTACT_C',
        'comments' => NULL,
        'help' => NULL,
        'module' => 'Cases',
        'type' => 'relate',
        'len' => '255',
        'required' => '0',
        'default_value' => NULL,
        'date_modified' => '2010-11-29 11:27:41',
        'deleted' => '0',
        'audited' => '0',
        'massupdate' => '0',
        'duplicate_merge' => '0',
        'reportable' => '1',
        'importable' => 'true',
        'ext1' => NULL,
        'ext2' => 'Contacts',
        'ext3' => 'contact_id_c',
        'ext4' => NULL,
      ),
      array (
        'name' => 'contact_id_c',
        'label' => 'LBL_CONTACT_ID_C',
        'comments' => NULL,
        'help' => NULL,
        'module' => 'Cases',
        'type' => 'id',
        'len' => '36',
        'required' => '0',
        'default_value' => NULL,
        'date_modified' => '2010-11-29 11:27:41',
        'deleted' => '0',
        'audited' => '0',
        'massupdate' => '0',
        'duplicate_merge' => '0',
        'reportable' => '0',
        'importable' => 'true',
        'ext1' => NULL,
        'ext2' => NULL,
        'ext3' => NULL,
        'ext4' => NULL,
      ),
      array (
        'name' => 'show_in_portal_c',
        'label' => 'LBL_SHOW_IN_PORTAL',
        'comments' => NULL,
        'help' => NULL,
        'module' => 'Cases',
        'type' => 'bool',
        'len' => '255',
        'required' => '0',
        'default_value' => '1',
        'date_modified' => '2010-11-29 11:27:41',
        'deleted' => '0',
        'audited' => '0',
        'massupdate' => '0',
        'duplicate_merge' => '0',
        'reportable' => '1',
        'importable' => 'true',
        'ext1' => NULL,
        'ext2' => NULL,
        'ext3' => NULL,
        'ext4' => NULL,
      ),
      array (
        'name' => 'show_in_portal_c',
        'label' => 'LBL_SHOW_IN_PORTAL',
        'comments' => NULL,
        'help' => NULL,
        'module' => 'Bugs',
        'type' => 'bool',
        'len' => '255',
        'required' => '0',
        'default_value' => '1',
        'date_modified' => '2010-11-29 11:27:43',
        'deleted' => '0',
        'audited' => '0',
        'massupdate' => '0',
        'duplicate_merge' => '0',
        'reportable' => '1',
        'importable' => 'true',
        'ext1' => NULL,
        'ext2' => NULL,
        'ext3' => NULL,
        'ext4' => NULL,
      ),
      array (
        'name' => 'show_in_portal_c',
        'label' => 'LBL_SHOW_IN_PORTAL',
        'comments' => NULL,
        'help' => NULL,
        'module' => 'Notes',
        'type' => 'bool',
        'len' => '255',
        'required' => '0',
        'default_value' => '1',
        'date_modified' => '2010-11-29 11:27:43',
        'deleted' => '0',
        'audited' => '0',
        'massupdate' => '0',
        'duplicate_merge' => '0',
        'reportable' => '1',
        'importable' => 'true',
        'ext1' => NULL,
        'ext2' => NULL,
        'ext3' => NULL,
        'ext4' => NULL,
      ),
      array (
        'name' => 'show_in_portal_c',
        'label' => 'LBL_SHOW_IN_PORTAL',
        'comments' => NULL,
        'help' => NULL,
        'module' => 'KBDocuments',
        'type' => 'bool',
        'len' => '255',
        'required' => '0',
        'default_value' => '1',
        'date_modified' => '2010-11-29 11:27:43',
        'deleted' => '0',
        'audited' => '0',
        'massupdate' => '0',
        'duplicate_merge' => '0',
        'reportable' => '1',
        'importable' => 'true',
        'ext1' => NULL,
        'ext2' => NULL,
        'ext3' => NULL,
        'ext4' => NULL,
      ),
      array (
        'name' => 'show_in_portal_c',
        'label' => 'LBL_SHOW_IN_PORTAL',
        'comments' => NULL,
        'help' => NULL,
        'module' => 'Contacts',
        'type' => 'bool',
        'len' => '255',
        'required' => '0',
        'default_value' => '1',
        'date_modified' => '2010-11-29 11:27:44',
        'deleted' => '0',
        'audited' => '0',
        'massupdate' => '0',
        'duplicate_merge' => '0',
        'reportable' => '1',
        'importable' => 'true',
        'ext1' => NULL,
        'ext2' => NULL,
        'ext3' => NULL,
        'ext4' => NULL,
      ),
      array (
        'name' => 'show_in_portal_c',
        'label' => 'LBL_SHOW_IN_PORTAL',
        'comments' => NULL,
        'help' => NULL,
        'module' => 'Accounts',
        'type' => 'bool',
        'len' => '255',
        'required' => '0',
        'default_value' => '1',
        'date_modified' => '2010-11-29 11:27:44',
        'deleted' => '0',
        'audited' => '0',
        'massupdate' => '0',
        'duplicate_merge' => '0',
        'reportable' => '1',
        'importable' => 'true',
        'ext1' => NULL,
        'ext2' => NULL,
        'ext3' => NULL,
        'ext4' => NULL,
      ),
	),
	'logic_hooks' =>
	array(
		array(
			'module' => 'Cases',
			'hook' => 'before_save',
			'order' => 1,
			'description' => 'cases_contacts',
			'file' => 'custom/modules/Cases/Caseslogic_hooks.php',
			'class' => 'Caseslogic_hooks',
			'function' => 'createCaseContactRelationship',
		),
	),
);
?>