	<?php
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004 - 2009 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

	$manifest = array (
		 'acceptable_sugar_versions' => 
		  array (
	     	
		  ),
		  'acceptable_sugar_flavors' =>
		  array(
		  	'CE', 'PRO','ENT'
		  ),
		  'readme'=>'',
		  'key'=>'oss',
		  'author' => 'qamrun',
		  'description' => '',
		  'icon' => '',
		  'is_uninstallable' => true,
		  'name' => 'Recruitment',
		  'published_date' => '2010-06-18 10:03:26',
		  'type' => 'module',
		  'version' => '1253009006',
		  'remove_tables' => 'prompt',
		  );
$installdefs = array (
  'id' => 'Recruitment',
  'beans' => 
  array (
    array (
      'module' => 'Eval_Evaluations',
      'class' => 'Eval_Evaluations',
      'path' => 'modules/Eval_Evaluations/Eval_Evaluations.php',
      'tab' => true,
    ),
    array (
      'module' => 'OSS_Job',
      'class' => 'OSS_Job',
      'path' => 'modules/OSS_Job/OSS_Job.php',
      'tab' => true,
    ), 
    
   
    
    array (
      'module' => 'OSS_TeamMember',
      'class' => 'OSS_TeamMember',
      'path' => 'modules/OSS_TeamMember/OSS_TeamMember.php',
      'tab' => true,
    ), 
    array (
      'module' => 'gaur_Candidates',
      'class' => 'gaur_Candidates',
      'path' => 'modules/gaur_Candidates/gaur_Candidates.php',
      'tab' => true,
    ),
    array (
      'module' => 'refer_References',
      'class' => 'refer_References',
      'path' => 'modules/refer_References/refer_References.php',
      'tab' => true,
    ),
    array (
      'module' => 'Refer_Referrals',
      'class' => 'Refer_Referrals',
      'path' => 'modules/Refer_Referrals/Refer_Referrals.php',
      'tab' => true,
    ), 
    array (
      'module' => 'emplo_Employer',
      'class' => 'emplo_Employer',
      'path' => 'modules/emplo_Employer/emplo_Employer.php',
      'tab' => true,
    ),
    
    array (
      'module' => 'Rec_Recruitment_Agency',
      'class' => 'Rec_Recruitment_Agency',
      'path' => 'modules/Rec_Recruitment_Agency/Rec_Recruitment_Agency.php',
      'tab' => true,
    ),
  ),
  'relationships' => array(
	 array(      
       'meta_data' => '<basepath>/SugarModules/relationships/emplo_employer_gaur_candidatesMetaData.php',
     ),
	 array(      
       'meta_data' => '<basepath>/SugarModules/relationships/eval_evaluations_callsMetaData.php',
     ),
	 array(      
       'meta_data' => '<basepath>/SugarModules/relationships/gaur_candidates_activities_callsMetaData.php',
     ),
	 array(      
       'meta_data' => '<basepath>/SugarModules/relationships/gaur_candidates_activities_emailsMetaData.php',
     ),
	 array(      
       'meta_data' => '<basepath>/SugarModules/relationships/gaur_candidates_activities_meetingsMetaData.php',
     ),
	 array(      
       'meta_data' => '<basepath>/SugarModules/relationships/gaur_candidates_activities_notesMetaData.php',
     ),
	 array(      
       'meta_data' => '<basepath>/SugarModules/relationships/gaur_candidates_activities_tasksMetaData.php',
     ),
	 array(      
       'meta_data' => '<basepath>/SugarModules/relationships/gaur_candidates_eval_evaluationsMetaData.php',
     ),
	 array(      
       'meta_data' => '<basepath>/SugarModules/relationships/gaur_candidates_oss_jobMetaData.php',
     ),
	 array(      
       'meta_data' => '<basepath>/SugarModules/relationships/gaur_candidates_refer_referralsMetaData.php',
     ),
	
	 array(      
       'meta_data' => '<basepath>/SugarModules/relationships/oss_teammember_project_1MetaData.php',
     ),
	 array(      
       'meta_data' => '<basepath>/SugarModules/relationships/oss_teammember_projectMetaData.php',
     ),
	 array(      
       'meta_data' => '<basepath>/SugarModules/relationships/refer_references_gaur_candidatesMetaData.php',
     ),
   ),

  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    array (
      'from' => '<basepath>/SugarModules/modules/emplo_Employer',
      'to' => 'modules/emplo_Employer',
    ),
	array (
      'from' => '<basepath>/SugarModules/modules/Eval_Evaluations',
      'to' => 'modules/Eval_Evaluations',
    ),
    array (
      'from' => '<basepath>/SugarModules/modules/gaur_Candidates',
      'to' => 'modules/gaur_Candidates',
    ),
	array (
      'from' => '<basepath>/SugarModules/modules/OSS_Job',
      'to' => 'modules/OSS_Job',
    ),
   
    array (
      'from' => '<basepath>/SugarModules/modules/Rec_Recruitment_Agency',
      'to' => 'modules/Rec_Recruitment_Agency',
    ),
	
	array (
      'from' => '<basepath>/SugarModules/modules/OSS_TeamMember',
      'to' => 'modules/OSS_TeamMember',
    ),
	array (
      'from' => '<basepath>/SugarModules/modules/refer_References',
      'to' => 'modules/refer_References',
    ),
    array (
      'from' => '<basepath>/SugarModules/modules/Refer_Referrals',
      'to' => 'modules/Refer_Referrals',
    ),    
	array (
      'from' => '<basepath>/SugarModules/custom/modules/emplo_Employer',
      'to' => 'modules/emplo_Employer',
    ),
    array (
      'from' => '<basepath>/SugarModules/custom/modules/Eval_Evaluations',
      'to' => 'modules/Eval_Evaluations',
    ),
    array (
      'from' => '<basepath>/SugarModules/custom/modules/gaur_Candidates',
      'to' => 'modules/gaur_Candidates',
    ),
	array (
      'from' => '<basepath>/SugarModules/custom/modules/OSS_Job',
      'to' => 'modules/OSS_Job',
    ),
	array (
      'from' => '<basepath>/SugarModules/custom/modules/OSS_TeamMember',
      'to' => 'modules/OSS_TeamMember',
    ),
	array (
      'from' => '<basepath>/SugarModules/custom/modules/refer_References',
      'to' => 'modules/refer_References',
    ),
    array (
      'from' => '<basepath>/SugarModules/custom/modules/Refer_Referrals',
      'to' => 'modules/Refer_Referrals',
    ),
    
    array (
      'from' => '<basepath>/SugarModules/custom/modules/Rec_Recruitment_Agency',
      'to' => 'modules/Rec_Recruitment_Agency',
    ),
    
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/Project/Ext',
      'to' => 'custom/Extension/modules/Project/Ext',
    ),  
  ),
  'language' => 
  array (
    array (
      'from' => '<basepath>/SugarModules/Extension/application/Ext/Language/en_us.lang.ext.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/emplo_Employer/Ext/Language/en_us.lang.ext.php',
      'to_module' => 'emplo_Employer',
      'language' => 'en_us',
    ),	
	array (
      'from' => '<basepath>/SugarModules/Extension/modules/Eval_Evaluations/Ext/Language/en_us.lang.ext.php',
      'to_module' => 'Eval_Evaluations',
      'language' => 'en_us',
    ),	
	array (
      'from' => '<basepath>/SugarModules/Extension/modules/gaur_Candidates/Ext/Language/en_us.lang.ext.php',
      'to_module' => 'gaur_Candidates',
      'language' => 'en_us',
    ),
	array (
      'from' => '<basepath>/SugarModules/Extension/modules/OSS_Job/Ext/Language/en_us.lang.ext.php',
      'to_module' => 'OSS_Job',
      'language' => 'en_us',
    ),	
	
	
	array (
      'from' => '<basepath>/SugarModules/Extension/modules/OSS_TeamMember/Ext/Language/en_us.lang.ext.php',
      'to_module' => 'OSS_TeamMember',
      'language' => 'en_us',
    ),	
	array (
      'from' => '<basepath>/SugarModules/Extension/modules/refer_References/Ext/Language/en_us.lang.ext.php',
      'to_module' => 'refer_References',
      'language' => 'en_us',
    ),	
	array (
      'from' => '<basepath>/SugarModules/Extension/modules/Refer_Referrals/Ext/Language/en_us.lang.ext.php',
      'to_module' => 'Refer_Referrals',
      'language' => 'en_us',
    ),
  ),
  
  
  'vardefs' => array(
     array(
       'from'  => '<basepath>/SugarModules/Extension/modules/emplo_Employer/Ext/Vardefs/vardefs.ext.php', 
       'to_module' => 'emplo_Employer',
     ),
	array(
       'from'  => '<basepath>/SugarModules/Extension/modules/Eval_Evaluations/Ext/Vardefs/vardefs.ext.php', 
       'to_module' => 'Eval_Evaluations',
     ),
	array(
       'from'  => '<basepath>/SugarModules/Extension/modules/gaur_Candidates/Ext/Vardefs/vardefs.ext.php', 
       'to_module' => 'gaur_Candidates',
     ),
	array(
       'from'  => '<basepath>/SugarModules/Extension/modules/OSS_Job/Ext/Vardefs/vardefs.ext.php', 
       'to_module' => 'OSS_Job',
     ),
	
	
	array(
       'from'  => '<basepath>/SugarModules/Extension/modules/OSS_TeamMember/Ext/Vardefs/vardefs.ext.php', 
       'to_module' => 'OSS_TeamMember',
     ),
	array(
       'from'  => '<basepath>/SugarModules/Extension/modules/refer_References/Ext/Vardefs/vardefs.ext.php', 
       'to_module' => 'refer_References',
     ),
	array(
       'from'  => '<basepath>/SugarModules/Extension/modules/Refer_Referrals/Ext/Vardefs/vardefs.ext.php', 
       'to_module' => 'Refer_Referrals',
     ),	 
   ),
  
   'layoutdefs' => array(
     array(
       'from'  => '<basepath>/SugarModules/Extension/modules/emplo_Employer/Ext/Layoutdefs/layoutdefs.ext.php',
       'to_module' => 'emplo_Employer',
     ),
	 array(
       'from'  => '<basepath>/SugarModules/Extension/modules/Eval_Evaluations/Ext/Layoutdefs/layoutdefs.ext.php',
       'to_module' => 'Eval_Evaluations',
     ),
	 array(
       'from'  => '<basepath>/SugarModules/Extension/modules/gaur_Candidates/Ext/Layoutdefs/layoutdefs.ext.php',
       'to_module' => 'gaur_Candidates',
     ),
	 array(
       'from'  => '<basepath>/SugarModules/Extension/modules/OSS_Job/Ext/Layoutdefs/layoutdefs.ext.php',
       'to_module' => 'OSS_Job',
     ),
	 array(
       'from'  => '<basepath>/SugarModules/Extension/modules/OSS_TeamMember/Ext/Layoutdefs/layoutdefs.ext.php',
       'to_module' => 'OSS_TeamMember',
     ),
	 array(
       'from'  => '<basepath>/SugarModules/Extension/modules/refer_References/Ext/Layoutdefs/layoutdefs.ext.php',
       'to_module' => 'refer_References',
     ),
	 
     
   ),   
   
   'custom_fields' => array(	 
	 array(
       'name'            => 'phone_c',
       'label'           => 'LBL_PHONE', 
       'type'            => 'phone',
       'max_size'        =>  25,
       'require_option'  => 'optional', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'phone_c',
       'audited'         => 0, 
       'module'          => 'refer_References',
     ),
     array(
       'name'            => 'designation_c',
       'label'           => 'LBL_DESIGNATION', 
       'type'            => 'varchar',
       'max_size'        =>  25,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'designation_c',
       'audited'         => 0, 
       'module'          => 'refer_References',
     ),
     array(
       'name'            => 'email_c',
       'label'           => 'LBL_EMAIL', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'email_c',
       'audited'         => 0, 
       'module'          => 'refer_References',
     ),
     array(
       'name'            => 'company_c',
       'label'           => 'LBL_COMPANY', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'company_c',
       'audited'         => 0, 
       'module'          => 'refer_References',
     ),
     array(
       'name'            => 'title_c',
       'label'           => 'LBL_TITLE', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'title_c',
       'audited'         => 0, 
       'module'          => 'refer_References',
     ),
     
     array(
       'name'            => 'resumeid_c',
       'label'           => 'LBL_RESUMEID', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'resumeid_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     
     array(
       'name'            => 'lastactivedate_c',
       'label'           => 'Date Of Birth', 
       'type'            => 'date',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'lastactivedate_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     
     array(
       'name'            => 'workexperienceyears_c',
       'label'           => 'LBL_WORKEXPERIENCEYEARS', 
       'type'            => 'varchar',
       'max_size'        =>  11,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'workexperienceyears_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     
      array(
       'name'            => 'workexperiencemonths_c',
       'label'           => 'LBL_WORKEXPERIENCEMONTHS', 
       'type'            => 'varchar',
       'max_size'        =>  11,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'workexperiencemonths_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     
     
     
     
     array(
       'name'            => 'functionalarea_c',
       'label'           => 'LBL_FUNCTIONALAREA', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'functionalarea_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     
     array(
       'name'            => 'currentlocation_c',
       'label'           => 'LBL_CURRENTLOCATION', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'currentlocation_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     
     array(
       'name'            => 'preferredlocation_c',
       'label'           => 'LBL_PREFERREDLOCATION', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'preferredlocation_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     
     array(
       'name'            => 'oops_c',
       'label'           => 'LBL_OOPS', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'oops_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     
     array(
       'name'            => 'php4_c',
       'label'           => 'LBL_PHP4', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'php4_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'currentdesignation_c',
       'label'           => 'LBL_CURRENTDESIGNATION', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'currentdesignation_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'annualsalary_c',
       'label'           => 'LBL_ANNUALSALARY', 
       'type'            => 'varchar',
       'max_size'        =>  25,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'annualsalary_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'ugcourse_c',
       'label'           => 'LBL_UGCOURSE', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'ugcourse_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'ugspecialization_c',
       'label'           => 'LBL_UGSPECIALIZATION', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'ugspecialization_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'uginstitute_c',
       'label'           => 'LBL_UGINSTITUTE', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'resumeid_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'pgcourse_c',
       'label'           => 'LBL_PGCOURSE', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'pgcourse_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'pgspecialization_c',
       'label'           => 'LBL_PGSPECIALIZATION', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'pgspecialization_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'pginstitute_c',
       'label'           => 'LBL_PGINSTITUTE', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'pginstitute_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'postpgcourse_c',
       'label'           => 'LBL_POSTPGCOURSE', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'postpgcourse_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'postpgspecialization_c',
       'label'           => 'LBL_POSTPGSPECIALIZATION', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'postpgspecialization_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     
     array(
       'name'            => 'postpginsitute_c',
       'label'           => 'LBL_POSTPGINSITUTE', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'postpginsitute_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'php5_c',
       'label'           => 'LBL_PHP5', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'php5_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'mysql_c',
       'label'           => 'LBL_MYSQL', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'mysql_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'drupal_c',
       'label'           => 'LBL_DRUPAL', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'drupal_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'xcart_c',
       'label'           => 'LBL_XCART', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'xcart_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'sugarcrm_c',
       'label'           => 'LBL_SUGARCRM', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'sugarcrm_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'linux_c',
       'label'           => 'LBL_LINUX', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'linux_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'zendframework_c',
       'label'           => 'LBL_ZENDFRAMEWORK', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'zendframework_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'symfonyframework_c',
       'label'           => 'LBL_SYMFONYFRAMEWORK', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'symfonyframework_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'cakephp_c',
       'label'           => 'LBL_CAKEPHP', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'cakephp_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'javascript_c',
       'label'           => 'LBL_JAVASCRIPT', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'javascript_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'java_c',
       'label'           => 'LBL_JAVA', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'java_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'cprogramming_c',
       'label'           => 'LBL_CPROGRAMMING', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'cprogramming_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'joomla_c',
       'label'           => 'LBL_JOOMLA', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'joomla_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'css_c',
       'label'           => 'LBL_CSS', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'css_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(       
       'name'            => 'officestatus_c',
		'label'           => 'LBL_OFFICESTATUS',
		'type'            => 'enum',
		'max_size'        =>  100,
		'require_option'  => 'optional',
		'default_value'   => '1',
		'ext1'            => 'officestatus_list',
		'ext2'            => '',
		'ext3'            => '',
	   'audited'         => 0,
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'expectedctc_c',
       'label'           => 'LBL_EXPECTEDCTC', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'expectedctc_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'offeredctc_c',
       'label'           => 'LBL_OFFEREDCTC', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'offeredctc_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'finalctc_c',
       'label'           => 'LBL_FINALCTC', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'finalctc_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'comment_c',
       'label'           => 'LBL_COMMENT', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'comment_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'joiningdate_c',
       'label'           => 'LBL_JOININGDATE', 
       'type'            => 'date',
       'max_size'        =>  '',
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'joiningdate_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'reasonforrejection_c',
       'label'           => 'LBL_REASONFORREJECTION', 
       'type'            => 'multienum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => 'reasonforrejection_list',
       'ext2'            => '',
       'ext3'            => 'reasonforrejection_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'referredby_c',
       'label'           => 'LBL_REFERREDBY', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => 'referredby_list',
       'ext2'            => '',
       'ext3'            => 'referredby_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'anyother_c',
       'label'           => 'LBL_ANYOTHER', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'anyother_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     
     
        
     
     array(
       'name'            => 'job_c',
       'label'           => 'LBL_JOB', 
       'type'            => 'relate',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => 'OSS_Job',
       'ext3'            => 'oss_job_id_c',
       //'id_name' => 'oss_job_id_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'oss_job_id_c',
       'label'           => 'LBL_LIST_RELATED_TO', 
       'type'            => 'id',
       'max_size'        =>  36,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'oss_job_id_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     
     
     
     array(
       'name'            => 'osscubeemployeereferer_c',
       'label'           => 'LBL_OSSCUBEEMPLOYEEREFERER', 
       'type'            => 'relate',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => 'OSS_TeamMember',
       'ext3'            => 'oss_teammember_id1_c',
       //'id_name' => 'oss_job_id_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'oss_teammember_id1_c',
       'label'           => 'LBL_LIST_RELATED_TO', 
       'type'            => 'id',
       'max_size'        =>  36,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'oss_teammember_id1_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     
     
     
     
     array(
       'name'            => 'recruitmentagency_c',
       'label'           => 'LBL_RECRUITMENTAGENCY', 
       'type'            => 'relate',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => 'Rec_Recruitment_Agency',
       'ext3'            => 'rec_recruitment_agency_id_c',
       //'id_name' => 'oss_job_id_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     array(
       'name'            => 'rec_recruitment_agency_id_c',
       'label'           => 'LBL_LIST_RELATED_TO', 
       'type'            => 'id',
       'max_size'        =>  36,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'rec_recruitment_agency_id_c',
       'audited'         => 0, 
       'module'          => 'gaur_Candidates',
     ),
     
     
     
     
     
     
     
     array(
       'name'            => 'nameofevaluator_c',
       'label'           => 'LBL_NAMEOFEVALUATOR', 
       'type'            => 'relate',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => 'OSS_TeamMember',
       'ext3'            => 'oss_teammember_id_c',
       //'id_name' => 'oss_teammember_id_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     array(
       'name'            => 'oss_teammember_id_c',
       'label'           => 'LBL_LIST_RELATED_TO', 
       'type'            => 'id',
       'max_size'        =>  36,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'oss_teammember_id_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'dateofevaluation_c',
       'label'           => 'LBL_DATEOFEVALUATION', 
       'type'            => 'date',
       'max_size'        =>  '',
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'dateofevaluation_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     array(
       'name'            => 'timeofevaluation_c',
       'label'           => 'LBL_TIMEOFEVALUATION', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'timeofevaluation_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'cmarks_c',
       'label'           => 'LBL_CMARKS', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'cmarks_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'php_c',
       'label'           => 'LBL_PHP', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'php_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     array(
       'name'            => 'english_c',
       'label'           => 'LBL_ENGLISH', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'english_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'logical_c',
       'label'           => 'LBL_LOGICAL', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'logical_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     array(
       'name'            => 'mode_c',
       'label'           => 'LBL_MODE', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'mode_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     array(
       'name'            => 'nextsteps_c',
       'label'           => 'LBL_NEXTSTEPS', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => 'nextstep__',
       'ext2'            => '',
       'ext3'            => 'nextsteps_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     array(
       'name'            => 'recommendations_c',
       'label'           => 'LBL_RECOMMENDATIONS', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => 'recommendation_list',
       'ext2'            => '',
       'ext3'            => 'recommendations_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     
     array(
       'name'            => 'javascript_c',
       'label'           => 'LBL_JAVASCRIPT', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'javascript_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'cakephp_c',
       'label'           => 'LBL_CAKEPHP', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'cakephp_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'symfonyframework_c',
       'label'           => 'LBL_SYMFONYFRAMEWORK', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'symfonyframework_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'zendframework_c',
       'label'           => 'LBL_ZENDFRAMEWORK', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'zendframework_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'linux_c',
       'label'           => 'LBL_LINUX', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'linux_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'sugarcrm_c',
       'label'           => 'LBL_SUGARCRM', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'sugarcrm_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'xcart_c',
       'label'           => 'LBL_XCART', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'xcart_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'drupal_c',
       'label'           => 'LBL_DRUPAL', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'drupal_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'mysql_c',
       'label'           => 'LBL_MYSQL', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'mysql_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'php5_c',
       'label'           => 'LBL_PHP5', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'php5_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'php4_c',
       'label'           => 'LBL_PHP4', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'php4_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'oops_c',
       'label'           => 'LBL_OOPS', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'oops_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'cselection_c',
       'label'           => 'LBL_CSELECTION', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'cselection_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'analytical_c',
       'label'           => 'LBL_ANALYTICAL', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'analytical_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'spokenenglish_c',
       'label'           => 'LBL_SPOKENENGLISH', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'spokenenglish_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'writtenenglish_c',
       'label'           => 'LBL_WRITTENENGLISH', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'writtenenglish_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'java_c',
       'label'           => 'LBL_JAVA', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'java_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'joomla_c',
       'label'           => 'LBL_JOOMLA', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'joomla_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'css_c',
       'label'           => 'LBL_CSS', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'css_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     array(
       'name'            => 'logical1_c',
       'label'           => 'LBL_LOGICAL1', 
       'type'            => 'enum',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => '', 
       'ext1'            => 'scaleselection_list',
       'ext2'            => '',
       'ext3'            => 'logical1_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     
     
      array(
       'name'            => 'nameofcandidate_c',
       'label'           => 'LBL_NAMEOFCANDIDATE', 
       'type'            => 'relate',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => 'gaur_Candidates',
       'ext3'            => 'gaur_candidates_id_c',
      // 'id_name' => 'gaur_candidates_id_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),
     array(
       'name'            => 'gaur_candidates_id_c',
       'label'           => 'LBL_LIST_RELATED_TO', 
       'type'            => 'id',
       'max_size'        =>  36,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'gaur_candidates_id_c',
       'audited'         => 0, 
       'module'          => 'Eval_Evaluations',
     ),    
     
     array(
       'name'            => 'noofcandidate_c',
       'label'           => 'LBL_NOOFCANDIDATE_C', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'noofcandidate_c',
       'audited'         => 0, 
       'module'          => 'OSS_Job',
     ),
     array(
       'name'            => 'no_ofvacancies_c',
       'label'           => 'LBL_NO_OFVACANCIES', 
       'type'            => 'varchar',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'no_ofvacancies_c',
       'audited'         => 0, 
       'module'          => 'OSS_Job',
     ),
     array(
       'name'            => 'targetdatetohire_c',
       'label'           => 'LBL_TARGETDATETOHIRE', 
       'type'            => 'date',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'targetdatetohire_c',
       'audited'         => 0, 
       'module'          => 'OSS_Job',
     ),
     
     
      array(
       'name'            => 'project_c',
       'label'           => 'LBL_PROJECT', 
       'type'            => 'relate',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => 'Project',
       'ext3'            => 'project_id_c',
      // 'id_name' => 'gaur_candidates_id_c',
       'audited'         => 0, 
       'module'          => 'OSS_Job',
     ),
     array(
       'name'            => 'project_id_c',
       'label'           => 'LBL_LIST_RELATED_TO', 
       'type'            => 'id',
       'max_size'        =>  36,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'project_id_c',
       'audited'         => 0, 
       'module'          => 'OSS_Job',
     ), 
     
     array(
       'name'            => 'client_c',
       'label'           => 'LBL_CLIENT', 
       'type'            => 'relate',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => 'Accounts',
       'ext3'            => 'account_id_c',
      // 'id_name' => 'gaur_candidates_id_c',
       'audited'         => 0, 
       'module'          => 'OSS_Job',
     ),
     array(
       'name'            => 'account_id_c',
       'label'           => 'LBL_LIST_RELATED_TO', 
       'type'            => 'id',
       'max_size'        =>  36,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'account_id_c',
       'audited'         => 0, 
       'module'          => 'OSS_Job',
     ), 
     
     array(
       'name'            => 'team_c',
       'label'           => 'LBL_TEAM', 
       'type'            => 'relate',
       'max_size'        =>  255,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => 'OSS_TeamMember',
       'ext3'            => 'oss_teammember_id_c',
       'audited'         => 0, 
       'module'          => 'OSS_Job',
     ),
     array(
       'name'            => 'oss_teammember_id_c',
       'label'           => 'LBL_LIST_RELATED_TO', 
       'type'            => 'id',
       'max_size'        =>  36,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'oss_teammember_id_c',
       'audited'         => 0, 
       'module'          => 'OSS_Job',
     ), 
     
      array(       
       'name'            => 'type_c',
		'label'           => 'LBL_TYPE',
		'type'            => 'enum',
		'max_size'        =>  100,
		'require_option'  => 'optional',
		'default_value'   => 'Permanent',
		'ext1'            => 'TeamMemberType_list',
		'ext2'            => '',
		'ext3'            => '',
	   'audited'         => 0,
       'module'          => 'OSS_TeamMember',
     ),
     
     array(       
       'name'            => 'status_c',
		'label'           => 'LBL_STATUS',
		'type'            => 'enum',
		'max_size'        =>  100,
		'require_option'  => 'optional',
		'default_value'   => 'Alumni',
		'ext1'            => 'Status_list',
		'ext2'            => '',
		'ext3'            => '',
	   'audited'         => 0,
       'module'          => 'OSS_TeamMember',
     ),
     
     array(       
       'name'            => 'billable_c',
		'label'           => 'LBL_BILLABLE',
		'type'            => 'enum',
		'max_size'        =>  100,
		'require_option'  => 'optional',
		'default_value'   => 'Billable',
		'ext1'            => 'Team_billable_list',
		'ext2'            => '',
		'ext3'            => '',
	   'audited'         => 0,
       'module'          => 'OSS_TeamMember',
     ),
     
     array(       
       'name'            => 'location_c',
		'label'           => 'LBL_LOCATION',
		'type'            => 'enum',
		'max_size'        =>  100,
		'require_option'  => 'optional',
		'default_value'   => '',
		'ext1'            => 'location_teammember',
		'ext2'            => '',
		'ext3'            => '',
	   'audited'         => 0,
       'module'          => 'OSS_TeamMember',
     ),
     
     
     array(
       'name'            => 'phone_c',
       'label'           => 'LBL_PHONE', 
       'type'            => 'phone',
       'max_size'        =>  25,
       'require_option'  => 'optional', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'phone_c',
       'audited'         => 0, 
       'module'          => 'Rec_Recruitment_Agency',
     ),
     
     array(
       'name'            => 'mobile_c',
       'label'           => 'LBL_MOBILE', 
       'type'            => 'phone',
       'max_size'        =>  25,
       'require_option'  => 'optional', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'mobile_c',
       'audited'         => 0, 
       'module'          => 'Rec_Recruitment_Agency',
     ),
     
     array(
       'name'            => 'otherphone_c',
       'label'           => 'LBL_OTHERPHONE', 
       'type'            => 'phone',
       'max_size'        =>  25,
       'require_option'  => 'optional', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'otherphone_c',
       'audited'         => 0, 
       'module'          => 'Rec_Recruitment_Agency',
     ),
     
     array(
       'name'            => 'agency_contact_person_c',
       'label'           => 'LBL_AGENCY_CONTACT_PERSON', 
       'type'            => 'varchar',
       'max_size'        =>  25,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'agency_contact_person_c',
       'audited'         => 0, 
       'module'          => 'Rec_Recruitment_Agency',
     ),
     
     array(
       'name'            => 'address_city_c',
       'label'           => 'LBL_ADDRESS_CITY', 
       'type'            => 'varchar',
       'max_size'        =>  25,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'address_city_c',
       'audited'         => 0, 
       'module'          => 'Rec_Recruitment_Agency',
     ),
     
     array(
       'name'            => 'address_state_c',
       'label'           => 'LBL_ADDRESS_STATE', 
       'type'            => 'varchar',
       'max_size'        =>  25,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'address_state_c',
       'audited'         => 0, 
       'module'          => 'Rec_Recruitment_Agency',
     ),
     
     array(
       'name'            => 'address_postalcode_c',
       'label'           => 'LBL_ADDRESS_POSTALCODE', 
       'type'            => 'varchar',
       'max_size'        =>  25,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'address_postalcode_c',
       'audited'         => 0, 
       'module'          => 'Rec_Recruitment_Agency',
     ),
     
     array(
       'name'            => 'address_country_c',
       'label'           => 'LBL_ADDRESS_COUNTRY', 
       'type'            => 'varchar',
       'max_size'        =>  25,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'address_country_c',
       'audited'         => 0, 
       'module'          => 'Rec_Recruitment_Agency',
     ),
     
     array(
       'name'            => 'address_c',
       'label'           => 'LBL_ADDRESS', 
       'type'            => 'varchar',
       'max_size'        =>  25,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'address_c',
       'audited'         => 0, 
       'module'          => 'Rec_Recruitment_Agency',
     ),
     
     array(
       'name'            => 'website_c',
       'label'           => 'LBL_WEBSITE', 
       'type'            => 'varchar',
       'max_size'        =>  25,
       'require_option'  => '', 
       'default_value'   => 'http://', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'website_c',
       'audited'         => 0, 
       'module'          => 'Rec_Recruitment_Agency',
     ),
     
     array(
       'name'            => 'email_c',
       'label'           => 'LBL_EMAIL', 
       'type'            => 'varchar',
       'max_size'        =>  25,
       'require_option'  => '', 
       'default_value'   => ' ', 
       'ext1'            => '',
       'ext2'            => '',
       'ext3'            => 'email_c',
       'audited'         => 0, 
       'module'          => 'Rec_Recruitment_Agency',
     ),
	),
);
